# tartan_drive:
#   odomtopics: "/odometry/filtered_odom"
#   imtopics: "/multisense/left/image_rect_color"
#   ang_offset: 1.5707963267948966 # pi/2
#   img_process_func: "process_tartan_img"
#   odom_process_func: "nav_to_xy_yaw"

# scand:
#   odomtopics: ["/odom", "/jackal_velocity_controller/odom"]
#   imtopics: ["/image_raw/compressed", "/camera/rgb/image_raw/compressed"]
#   ang_offset: 0.0
#   img_process_func: "process_scand_img"
#   odom_process_func: "nav_to_xy_yaw"

# ros2 datasets below:
rclue:
  odomtopic: "/odom"
  imgtopic: "/image_raw"
  ang_offset: 0.0
  img_process_func: "process_scand_img"
  odom_process_func: "nav_to_xy_yaw"